name: 'Deployment State Tracking'
description: 'Track deployment state and coordinate rollback procedures'

inputs:
  action:
    description: 'Action to perform: track, get, reset'
    required: true
  service:
    description: 'Service name'
    required: true
  environment:
    description: 'Environment name'
    required: true
  version:
    description: 'Deployment version'
    required: false
  status:
    description: 'Deployment status: success, failed, rollback'
    required: false
  health_status:
    description: 'Health check status: passed, failed'
    required: false
  aws_region:
    description: 'AWS region for DynamoDB'
    required: false
    default: 'us-east-1'

outputs:
  current_version:
    description: 'Current deployed version'
    value: ${{ steps.get-state.outputs.current_version }}
  previous_version:
    description: 'Previous stable version'
    value: ${{ steps.get-state.outputs.previous_version }}
  failure_count:
    description: 'Current failure count'
    value: ${{ steps.get-state.outputs.failure_count }}
  last_successful_deployment:
    description: 'Timestamp of last successful deployment'
    value: ${{ steps.get-state.outputs.last_successful }}

runs:
  using: 'composite'
  steps:
    - name: Setup deployment state table
      if: inputs.action == 'track'
      shell: bash
      run: |
        # Ensure DynamoDB table exists for deployment state tracking
        TABLE_NAME="pdf-accessibility-deployment-state"

        # Check if table exists
        if ! aws dynamodb describe-table --table-name $TABLE_NAME --region ${{ inputs.aws_region }} >/dev/null 2>&1; then
          echo "Creating deployment state table..."
          aws dynamodb create-table \
            --table-name $TABLE_NAME \
            --attribute-definitions \
              AttributeName=service_env,AttributeType=S \
              AttributeName=timestamp,AttributeType=S \
            --key-schema \
              AttributeName=service_env,KeyType=HASH \
              AttributeName=timestamp,KeyType=RANGE \
            --billing-mode PAY_PER_REQUEST \
            --region ${{ inputs.aws_region }}

          # Wait for table to be active
          aws dynamodb wait table-exists --table-name $TABLE_NAME --region ${{ inputs.aws_region }}
        fi

    - name: Track deployment state
      if: inputs.action == 'track'
      shell: bash
      run: |
        TABLE_NAME="pdf-accessibility-deployment-state"
        SERVICE_ENV="${{ inputs.service }}-${{ inputs.environment }}"
        TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

        # Create deployment record
        aws dynamodb put-item \
          --table-name $TABLE_NAME \
          --item '{
            "service_env": {"S": "'$SERVICE_ENV'"},
            "timestamp": {"S": "'$TIMESTAMP'"},
            "version": {"S": "${{ inputs.version || 'unknown' }}"},
            "status": {"S": "${{ inputs.status || 'unknown' }}"},
            "health_status": {"S": "${{ inputs.health_status || 'unknown' }}"},
            "commit_sha": {"S": "${{ github.sha }}"},
            "workflow_run_id": {"S": "${{ github.run_id }}"},
            "actor": {"S": "${{ github.actor }}"}
          }' \
          --region ${{ inputs.aws_region }}

        echo "Deployment state tracked for $SERVICE_ENV"

    - name: Get deployment state
      if: inputs.action == 'get'
      id: get-state
      shell: bash
      run: |
        TABLE_NAME="pdf-accessibility-deployment-state"
        SERVICE_ENV="${{ inputs.service }}-${{ inputs.environment }}"

        # Get recent deployment records
        RECORDS=$(aws dynamodb query \
          --table-name $TABLE_NAME \
          --key-condition-expression "service_env = :service_env" \
          --expression-attribute-values '{":service_env": {"S": "'$SERVICE_ENV'"}}' \
          --scan-index-forward false \
          --limit 10 \
          --region ${{ inputs.aws_region }} \
          --output json)

        # Extract current and previous versions
        CURRENT_VERSION=$(echo "$RECORDS" | jq -r '.Items[0].version.S // "unknown"')
        PREVIOUS_VERSION=$(echo "$RECORDS" | jq -r '.Items[1].version.S // "unknown"')

        # Count recent failures
        FAILURE_COUNT=$(echo "$RECORDS" | jq '[.Items[] | select(.status.S == "failed")] | length')

        # Get last successful deployment
        LAST_SUCCESSFUL=$(echo "$RECORDS" | jq -r '.Items[] | select(.status.S == "success") | .timestamp.S' | head -1)

        echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "previous_version=$PREVIOUS_VERSION" >> $GITHUB_OUTPUT
        echo "failure_count=$FAILURE_COUNT" >> $GITHUB_OUTPUT
        echo "last_successful=$LAST_SUCCESSFUL" >> $GITHUB_OUTPUT

    - name: Reset failure count
      if: inputs.action == 'reset'
      shell: bash
      run: |
        TABLE_NAME="pdf-accessibility-deployment-state"
        SERVICE_ENV="${{ inputs.service }}-${{ inputs.environment }}"
        TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

        # Add a reset record
        aws dynamodb put-item \
          --table-name $TABLE_NAME \
          --item '{
            "service_env": {"S": "'$SERVICE_ENV'"},
            "timestamp": {"S": "'$TIMESTAMP'"},
            "version": {"S": "${{ inputs.version || 'reset' }}"},
            "status": {"S": "reset"},
            "health_status": {"S": "reset"},
            "commit_sha": {"S": "${{ github.sha }}"},
            "workflow_run_id": {"S": "${{ github.run_id }}"},
            "actor": {"S": "${{ github.actor }}"}
          }' \
          --region ${{ inputs.aws_region }}

        echo "Failure count reset for $SERVICE_ENV"

    - name: Generate state summary
      shell: bash
      run: |
        echo "=== Deployment State Summary ==="
        echo "Service: ${{ inputs.service }}"
        echo "Environment: ${{ inputs.environment }}"
        echo "Action: ${{ inputs.action }}"

        if [ "${{ inputs.action }}" == "get" ]; then
          echo "Current Version: ${{ steps.get-state.outputs.current_version }}"
          echo "Previous Version: ${{ steps.get-state.outputs.previous_version }}"
          echo "Failure Count: ${{ steps.get-state.outputs.failure_count }}"
          echo "Last Successful: ${{ steps.get-state.outputs.last_successful }}"
        fi
